version: '3.8'

services:
  db:
    container_name: bankapp-db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./back-end/config/.env
    networks:
      - bankapp-network
    command: postgres -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --quiet --dbname=$${POSTGRES_DB}--username=$${POSTGRES_USER} || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  backend:
    build:
      context: ./back-end
    command: >
      bash -c "python manage.py makemigrations bankapp && 
      python manage.py migrate && 
      python manage.py initproducts && 
      python manage.py initusers &&
      python manage.py runserver 0.0.0.0:8000"
    container_name: backend-container
    volumes:
      - ./backend/:/back-end/
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DB_HOST=bankapp-db
      - DB_PORT=5432
    networks:
      - bankapp-network
  frontend:
    build:
      context: ./front-end
    container_name: frontend-container
    depends_on:
      - db
      - backend
    ports:
      - '4200:4200'
    networks:
      - bankapp-network
volumes:
  postgres_data:
networks:
  bankapp-network:
    driver: bridge

# todo configure nginx server
