version: '3.8'

services:
  db:
    container_name: bankapp-db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./back-end/config/.env
    networks:
      - bankapp-network
    command: postgres -c listen_addresses='*'
  backend:
    build:
      context: ./back-end
    command: >
      bash -c "python3 manage.py migrate && python3 manage.py initproducts && python3 manage.py initusers &&
      python3 manage.py runserver 0.0.0.0:8000"
    container_name: backend-container
    volumes:
      - ./backend/:/back-end/
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DB_HOST=bankapp-db
      - DB_PORT=5432
    networks:
      - bankapp-network
  frontend:
    build:
      context: ./front-end
    container_name: frontend-container
    depends_on:
      - db
      - backend
    ports:
      - '4200:4200'
    networks:
      - bankapp-network
volumes:
  postgres_data:
networks:
  bankapp-network:
    driver: bridge

# todo configure nginx server
