version: '3.8'

services:
  backend:
    build:
      context: ./back-end
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/back-end/
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'bankproject'
volumes:
  postgres_data:

